import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-screen w-full relative">
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem={true}>
          {/* Dark Dot Matrix */}
          <div
            className="absolute inset-0 -z-1"
            style={{
              backgroundColor: "#0a0a0a",
              backgroundImage: `
                radial-gradient(circle at 25% 25%, #222222 0.5px, transparent 1px),
                radial-gradient(circle at 75% 75%, #111111 0.5px, transparent 1px)
              `,
              backgroundSize: "10px 10px",
              imageRendering: "pixelated",
            }}
          />
          
            {/* Your Content Here */}
            {children}
          </ThemeProvider>
        </div>
      </body>
    </html>
  );
}
